# Generated by Django 3.2.2 on 2021-05-24 08:54

import click_and_table.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_and_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(default=click_and_table.models.generate_reservation_code, max_length=64),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='vote',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_to',
            field=models.TimeField(null=True),
        ),
    ]
