# Generated by Django 3.2.2 on 2021-05-19 12:45

import click_and_table.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_and_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(default=click_and_table.models.generate_reservation_code, max_length=64),
        ),
        migrations.AlterField(
            model_name='rating',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=3),
        ),
    ]
