# Generated by Django 3.2.2 on 2021-05-21 08:16

import click_and_table.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_and_table', '0002_auto_20210519_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_to',
            field=models.TimeField(null=True),
        ),
    ]
