# Generated by Django 3.2.2 on 2021-05-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_and_table', '0003_auto_20210521_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='vote',
            field=models.SmallIntegerField(default=0),
        ),
    ]
