# Generated by Django 3.2.2 on 2021-05-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_and_table', '0003_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='/static/images/no-image.png', upload_to=''),
        ),
    ]
