# Generated by Django 3.2.2 on 2021-05-22 07:56

import click_and_table.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_and_table', '0004_alter_rating_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=click_and_table.models.Restaurant.average_rating, max_digits=2),
        ),
    ]
